### ISSUE TITLE
Use Weak account key instead of account keys

### ISSUE THREAD

**Issue by wimel** [vdo/DAppNodePackage-boinc#1]
In the step [Get you project key](https://github.com/vdo/DAppNodePackage-boinc#get-your-project-key) it would be a good option to clarify that the key to be used is `Weak account key` not `account key` 

**Thanks for this package!!** My personal DAppNode is running with Boinc, and the node of ColmenaLabs_svq is running with this package too, thanks for your work!!

By the way, is better install the package using de Store of DAppNode, with the link provided in this repo doesn't appear the correct link to the rosetta project. In case this help to someone this is the link to rosetta:

`http://boinc.bakerlab.org/rosetta/`

![roseta](https://user-images.githubusercontent.com/17170149/76883898-1a51f180-687d-11ea-9e83-ff69df3b0acd.png)

**Comment by vdo** [comment]
Thanks for the heads up and for contributing!

Link fixed too
