### ISSUE TITLE
BOINC client uses only 1 of 16 cpus available

### ISSUE THREAD

**Issue by uniconstructor** [vdo/DAppNodePackage-boinc#2]
I am installed BOINC package for dappnode, but I noticed that BOINC client uses only 1 of 16 CPUs available.

Usually I'm overriding default BOINC settings using script:
```sh
(sudo sh -c "wget https://gist.githubusercontent.com/uniconstructor/a94b0d8020ec22669775a728376b422e/raw/ad2e85b64fbfab06e34abb5333ef8eab2dbe3352/boinc.xml -O /var/lib/boinc-client/global_prefs_override.xml") && (boinccmd --read_global_prefs_override)
```

Currently, I need to set **max_cpus** option, but I can't do this because default security settings of DAppNode package doesn't allow ssh login from root, and default user (dappnode) "not in sudoers file", so I can't modify `/var/lib/boinc-client/global_prefs_override.xml`.

There is also no command-line options for settings "max_cpus" config.

How can I force BOINC client to use all 16 available CPU's?

Full BOINC client options list (if needed):
- https://boinc.berkeley.edu/wiki/Global_prefs_override.xml
- https://boinc.berkeley.edu/wiki/Client_configuration

**Comment by uniconstructor** [comment]
Also: I'm checked out the code - BOINC runs inside a Docker container.
Does DAppNode core have any constraints for BOINC on a Docker level (like described there: https://docs.docker.com/config/containers/resource_constraints/#cpu )?

**Comment by vdo** [comment]
Hi @uniconstructor 

The CPU number usage is not limited by package. You can change the settings of your BOINC node with BOINC Manager app, using the login:

server: boinc.public.dappnode
password: dappnode

It would be nice to be able to configure this with the package itself, so I will keep this issue open to add such feature.

**Comment by vdo** [comment]
My package is using all CPU cores by default. Are you sure it's using only one core? 
It takes some time to download the jobs and use all of them

**Comment by uniconstructor** [comment]
Closing issue: digging deeper I found this problem is not related to BOINC package. It was caused by rare combination of motherboard BIOS settings and Debian kernel flags: https://askubuntu.com/questions/247028/how-to-fix-that-only-one-out-of-four-cores-of-my-cpu-is-detected
